name: Test with Nondex
run-name: Known Flaky test
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test
        run: mvn -pl nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers -am test -Dtest=org.apache.nifi.ldap.tenants.LdapUserGroupProviderTest -DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test
        run: mvn -pl nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers -am edu.illinois:nondex-maven-plugin:2.1.1:nondex -DnondexRuns=15 -Dtest=org.apache.nifi.ldap.tenants.LdapUserGroupProviderTest -DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false

